### ISSUE TITLE
JIT compilation errror using "@angular/cli": "^9.0.0-rc.6"

### ISSUE THREAD

**Issue by st-clair-clarke** [cedx/ngx-webstorage.js#1]
Hi, 
I am using "@angular/cli": "^9.0.0-rc.6" and supporting packages. These use the new Ivy compiler and mandatory AOT compilation.

When ever I attempt to inject LocalStorage into my component using the constructor, I get the following error

`
core.js:6382 ERROR Error: Uncaught (in promise): Error: Angular JIT compilation failed: '@angular/compiler' not loaded!
  - JIT compilation is discouraged for production use-cases! Consider AOT mode instead.
  - Did you bootstrap using '@angular/platform-browser-dynamic' or '@angular/platform-server'?
  - Alternatively provide the compiler with 'import "@angular/compiler";' before bootstrapping.
Error: Angular JIT compilation failed: '@angular/compiler' not loaded!
  - JIT compilation is discouraged for production use-cases! Consider AOT mode instead.
  - Did you bootstrap using '@angular/platform-browser-dynamic' or '@angular/platform-server'?
  - Alternatively provide the compiler with 'import "@angular/compiler";' before bootstrapping.
    at getCompilerFacade (core.js:573)
    at Function.get (core.js:18048)
    at getInjectableDef (core.js:362)
    at R3Injector.get (core.js:18479)
    at NgModuleRef$1.get (core.js:36352)
    at Object.get (core.js:34179)
    at getOrCreateInjectable (core.js:6007)
    at Module.ɵɵdirectiveInject (core.js:22704)
    at NodeInjectorFactory.RegistrationPrefsComponent_Factory [as factory] (registration-prefs.component.ts:87)
    at getNodeInjectable (core.js:6152)
    at resolvePromise (zone-evergreen.js:793)
    at resolvePromise (zone-evergreen.js:752)
    at zone-evergreen.js:854
    at ZoneDelegate.invokeTask (zone-evergreen.js:400)
    at Object.onInvokeTask (core.js:41410)
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Zone.runTask (zone-evergreen.js:168)
    at drainMicroTaskQueue (zone-evergreen.js:570)
    at invokeTask (zone-evergreen.js:485)
    at ZoneTask.invoke (zone-evergreen.js:470)
defaultErrorLogger @ core.js:6382
handleError @ core.js:6435
next @ core.js:42365
schedulerFn @ core.js:37138
__tryOrUnsub @ Subscriber.js:183
next @ Subscriber.js:122
_next @ Subscriber.js:72
next @ Subscriber.js:49
next @ Subject.js:39
emit @ core.js:37100
(anonymous) @ core.js:41472
invoke @ zone-evergreen.js:365
run @ zone-evergreen.js:124
runOutsideAngular @ core.js:41268
onHandleError @ core.js:41469
handleError @ zone-evergreen.js:369
runGuarded @ zone-evergreen.js:137
api.microtaskDrainDone @ zone-evergreen.js:671
drainMicroTaskQueue @ zone-evergreen.js:577
invokeTask @ zone-evergreen.js:485
ZoneTask.invoke @ zone-evergreen.js:470
timer @ zone-evergreen.js:2535
setTimeout (async)
scheduleTask @ zone-evergreen.js:2556
scheduleTask @ zone-evergreen.js:386
onScheduleTask @ zone-evergreen.js:273
scheduleTask @ zone-evergreen.js:379
scheduleTask @ zone-evergreen.js:211
scheduleMacroTask @ zone-evergreen.js:234
scheduleMacroTaskWithCurrentZone @ zone-evergreen.js:1118
(anonymous) @ zone-evergreen.js:2569
proto.<computed> @ zone-evergreen.js:1433
(anonymous) @ medsoft-app-load.service.ts:28
ZoneAwarePromise @ zone-evergreen.js:872
initializeMedsoftApp @ medsoft-app-load.service.ts:25
(anonymous) @ app-load.module.ts:7
runInitializers @ core.js:40525
(anonymous) @ core.js:42372
_callAndReportToErrorHandler @ core.js:42533
(anonymous) @ core.js:42366
invoke @ zone-evergreen.js:365
onInvoke @ core.js:41432
invoke @ zone-evergreen.js:364
run @ zone-evergreen.js:124
run @ core.js:41207
bootstrapModuleFactory @ core.js:42335
(anonymous) @ core.js:42411
invoke @ zone-evergreen.js:365
run @ zone-evergreen.js:124
(anonymous) @ zone-evergreen.js:851
invokeTask @ zone-evergreen.js:400
runTask @ zone-evergreen.js:168
drainMicroTaskQueue @ zone-evergreen.js:570
Promise.then (async)
scheduleMicroTask @ zone-evergreen.js:553
scheduleTask @ zone-evergreen.js:389
scheduleTask @ zone-evergreen.js:211
scheduleMicroTask @ zone-evergreen.js:231
scheduleResolveOrReject @ zone-evergreen.js:841
then @ zone-evergreen.js:967
bootstrapModule @ core.js:42407
./src/main.ts @ main.ts:19
__webpack_require__ @ bootstrap:84
0 @ main.ts:21
__webpack_require__ @ bootstrap:84
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.js:1
`

Removing the package and reinstall give the same error. What do you think is wrong?

**Comment by cedx** [comment]
You don't seem to use AOT compilation...

```
core.js:6382 ERROR Error: Uncaught (in promise): Error: Angular JIT compilation failed: '@angular/compiler' not loaded!

    JIT compilation is discouraged for production use-cases! Consider AOT mode instead.
```

This error does not seem to be tie to my library.
